-- ULM QB Conflict Defender v6.6 cloud persistence
-- Run this ONCE in Supabase SQL Editor before deploying v6.6.

create table if not exists public.qb_conflict_results (
  id bigint generated by default as identity primary key,
  qb_profile_id text not null,
  question_id text null,
  mode text not null check (mode in ('practice','live')),
  correct_count smallint not null check (correct_count between 0 and 2),
  response_time numeric(6,3) not null check (response_time >= 0 and response_time <= 6),
  points integer not null default 0 check (points >= 0 and points <= 1000),
  room_code text null,
  game_score integer null,
  played_at timestamptz not null default now()
);

create index if not exists qb_conflict_results_profile_idx
  on public.qb_conflict_results(qb_profile_id);

create index if not exists qb_conflict_results_played_idx
  on public.qb_conflict_results(played_at desc);

alter table public.qb_conflict_results enable row level security;

drop policy if exists "QB devices read conflict results" on public.qb_conflict_results;
drop policy if exists "QB devices insert conflict results" on public.qb_conflict_results;

create policy "QB devices read conflict results"
on public.qb_conflict_results
for select
to anon, authenticated
using (true);

create policy "QB devices insert conflict results"
on public.qb_conflict_results
for insert
to anon, authenticated
with check (
  qb_profile_id in (
    'landon-graves',
    'aidan-armenta',
    'austin-carlisle',
    'bryson-kimbrough',
    'ty-purdy',
    'taylor-dupuis',
    'brayden-burkhardt',
    'tommy-denison'
  )
  and mode in ('practice','live')
  and correct_count between 0 and 2
  and response_time between 0 and 6
  and points between 0 and 1000
);

-- Results are append-only from player devices.
-- There are intentionally no anonymous update/delete policies.
