-- ULM QB Conflict Defender cloud profile stats v6.4
create table if not exists public.qb_profile_results (
  id bigint generated by default as identity primary key,
  qb_profile_id text not null,
  question_id uuid null references public.qb_questions(id) on delete set null,
  mode text not null check (mode in ('practice','live')),
  correct_count smallint not null check (correct_count between 0 and 2),
  response_time numeric(6,3) not null check (response_time >= 0 and response_time <= 6),
  points integer not null default 0 check (points >= 0),
  room_code text null,
  played_at timestamptz not null default now()
);

create index if not exists qb_profile_results_profile_idx on public.qb_profile_results(qb_profile_id);
create index if not exists qb_profile_results_played_idx on public.qb_profile_results(played_at desc);

alter table public.qb_profile_results enable row level security;

drop policy if exists "QB devices can read profile results" on public.qb_profile_results;
drop policy if exists "QB devices can insert profile results" on public.qb_profile_results;

create policy "QB devices can read profile results"
on public.qb_profile_results
for select
to anon, authenticated
using (true);

create policy "QB devices can insert profile results"
on public.qb_profile_results
for insert
to anon, authenticated
with check (
  qb_profile_id in (
    'landon-graves',
    'aidan-armenta',
    'austin-carlisle',
    'bryson-kimbrough',
    'ty-purdy',
    'taylor-dupuis',
    'brayden-burkhardt',
    'tommy-denison'
  )
  and mode in ('practice','live')
  and correct_count between 0 and 2
  and response_time between 0 and 6
  and points between 0 and 1000
);
